app_name   = rbac
# possible values: DEBUG, INFO, WARNING, ERROR, FATAL

[mysql]
ip       = 192.168.0.6
port     = 3306
user     = root
password = Wsw1433223.
database = ginxiaomirbac

[consul]
addr   = 127.0.0.1:8500

